# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: EStockAgentPool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       $path = "$(Build.SourcesDirectory)"
#       write-host "path-$path"
#       $test = Get-ChildItem -Path $path -file -Recurse -force
#       foreach($t in $test){
#        write-host "$($t.fullname)"
#       }

- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
      command: "publish"
      zipAfterPublish: false
      arguments: -c=Release o=build
- task: Docker@2
  inputs:
    containerRegistry: 'DockerServiceConnection'
    repository: 'estock'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/CompanyMicroService/Dockerfile'
